name: assess modernisation effort

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  assess:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install appcat
      run: dotnet tool install -g dotnet-appcat
    - name: Configure telemetry permissions
      run: set DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT="1"
    - name: Run appcat JSON
      run: appcat analyze "./app" --source folder --report appcat-results/reports --serializer json --non-interactive --code --binaries --target AppService.Linux
    - name: Run appcat HTML
      run: appcat analyze "./app" --source folder --report appcat-results/reports/html --serializer html --non-interactive --code --binaries --target AppService.Linux
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        path: appcat-results/


