name: assess modernisation effort
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOTNET_APPCAT_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT: 1
  DOTNET_UPGRADEASSISTANT_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  assess:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install appcat
      run: dotnet tool install -g dotnet-appcat
    - name: print
      run: echo "$DOTNET_APPCAT_TELEMETRY_OPTOUT"
    - name: Run appcat JSON
      run: appcat analyze "./app" --source folder --report appcat-results/reports --serializer json --non-interactive --code --binaries --target AppService.Linux
    - name: Run appcat HTML
      run: appcat analyze "./app" --source folder --report appcat-results/reports/html --serializer html --non-interactive --code --binaries --target AppService.Linux
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        path: appcat-results/


